services:
  cloudflared:
    container_name: cloudflare-container
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN}
    environment:
      - CF_TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    networks:
      - app-network

  backend:
    container_name: ${CONTAINER_NAME_BACKEND}
    image: ${IMAGE_NAME_BACKEND}
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - NODE_ENV=production
      - CONTAINER_NAME=${CONTAINER_NAME_BACKEND}
      - IMAGE_NAME=${IMAGE_NAME_BACKEND}
  
  frontend:
    container_name: ${CONTAINER_NAME_FRONTEND}
    image: ${IMAGE_NAME_FRONTEND}
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - CONTAINER_NAME=${CONTAINER_NAME_FRONTEND}
      - IMAGE_NAME=${IMAGE_NAME_FRONTEND}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge