services:
  cloudflared:
    container_name: cloudflare-container
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN}
    environment:
      - CF_TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    networks:
      - react-app-network

  react-app:
    container_name: ${CONTAINER_NAME}
    image: ${IMAGE_NAME}
    build: .
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production  # Optional, set your app environment
      - CONTAINER_NAME=${CONTAINER_NAME}
      - IMAGE_NAME=${IMAGE_NAME}
    networks:
      - react-app-network

networks:
  react-app-network:
    driver: bridge