services:
  cloudflared:
    container_name: cloudflare-container
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN}
    environment:
      - CF_TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    networks:
      - react-app-network

  react-app:
    #container_name: reac-app-container
    #image: market-fractals-site/market-fractals:v1.0
    build: .
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production  # Optional, set your app environment
    networks:
      - react-app-network

networks:
  react-app-network:
    driver: bridge