name: Build and Deploy React App

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
      
      - name: Set up Docker Compose
        run: docker-compose -f compose.yml up --build -d

  deploy:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    # Copy Docker image to server and deploy
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ssh.marketfractals.com  # The Cloudflare Tunnel hostname
          username: ${{ secrets.USER }}
          key: ${{ secrets.MARKETFRACTALS_GITHUB_SSH_KEY }}
          ports: "22:22"
          script: |
            git pull origin main
            docker-compose up --build -d