name: Build and Deploy React App

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: docker-compose -f compose.yml up --build -d

  deploy:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    # Copy Docker image to server and deploy
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Wrangler Globally
        run: npm install -g wrangler@3.15.0
      
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          wrangler_version: "3.15.0"
          apiToken: ${{ secrets.CLOUDFLARE_API }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Run Docker container
        run: ssh -i ${{ secrets.MARKETFRACTALS_GITHUB_SSH_KEY }} ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}@${{ secrets.CLOUDFLARE_API }} \
          "docker-compose -f ~/my-react-app/docker-compose.yml up -d"
    
      - name: Start Cloudflare Tunnel
        run: ssh -i ${{ secrets.MARKETFRACTALS_GITHUB_SSH_KEY }} ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}@${{ secrets.CLOUDFLARE_API }} \
          "cloudflared tunnel run my-react-app"